experiment_name: task3_claude_MSA 

model:
  type: claude            #model handler type as written in models/__init__.py
  name: claude-opus-4-6  # just as it appears in huggingface

cache_dir: /scratch/ca2627/huggingface #modify to your own cache directory

dataset:
  path: datasets/task3/msa.json   #path to dataset JSON file
  instruction_path: prompts/task3-MSA.txt  #path to instruction file (default.txt)

task:
  type: dialogue_completion              #task 1: mcq or task 2: answer_generation
  max_tokens: 256

judge:
  prompt_path: prompts/judge-task3.txt            # 4-axis (non-binary) judge for task 3

output:
  predictions_path: results/predictions/task3/MSA/claude.csv #specify output pred file
  metrics_path: results/metrics/task3/MSA/claude.json  #specift output pred file


