experiment_name: task1_gpt5 

model:
  type: openai           #model handler type as written in models/__init__.py
  name: gpt-5.2  # just as it appears in huggingface

cache_dir: /scratch/ca2627/huggingface #modify to your own cache directory

dataset:
  path: datasets/answer-gen/test.json   #path to dataset JSON filexww
  instruction_path: prompts/task2.txt  #path to instruction file (default.txt)

task:
  type: answer_generation                #task 1: mcq or task 2: answer_generation

output:
  predictions_path: results/predictions/task2/test/medgemma.csv #specify output pred file
  metrics_path: results/metrics/task2/test/medgemma.json  #specift output pred file

