experiment_name: task2_medgemma

model:
  type: medgemma           #model handler type as written in models/__init__.py
  name: google/medgemma-27b-text-it  # just as it appears in huggingface

cache_dir: /scratch/netid/huggingface #modify to your own cache directory

dataset:
  path: datasets/answer-gen/medarabenchv2.json   #path to dataset JSON filexww
  instruction_path: prompts/task2.txt  #path to instruction file (default.txt)

task:
  type: answer_generation                #task 1: mcq or task 2: answer_generation

judge:
  prompt_path: prompts/judge-task2.txt

output:
  predictions_path: results/predictions/task2/medarabenchv2/medgemma.csv #specify output pred file
  metrics_path: results/metrics/task2/medarabenchv2/medgemma.json  #specift output pred file

