experiment_name: task1_gemini

model:
  type: gemini           #model handler type as written in models/__init__.py
  name: gemini-2.5-flash  # just as it appears in huggingface 

cache_dir: /scratch/ca2627/huggingface #modify to your own cache directory

dataset:
  path: datasets/qa/medarabench.json   #path to dataset JSON file
  instruction_path: prompts/task1-2.txt  #path to instruction file (default.txt)

task:
  type: mcq                #task 1: mcq or task 2: answer_generation

output:
  predictions_path: results/predictions/task1/medarabench/gemini.csv #specify output pred file
  metrics_path: results/metrics/task1/medarabench/gemini.json  #specift output pred file


